spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/board
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create #실행시점에 테이블을 드랍하고 다시 생성
    properties:
      hibernate:
        #show_sql: true # System.out 으로 sql을 남김
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug # logger을 통해 hibernate 실행 sql을 남김